name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Restore NuGet Packages
        run: dotnet restore Bls.sln
      
      - name: Build Solution
        run: dotnet build Bls.sln -c Release
      
      - name: Run Tests
        run: dotnet test Bls.sln --no-build -c Release --verbosity normal
      
      - name: Publish Web API
        run: dotnet publish BlsApi/BlsApi.csproj -c Release --no-build
      
      - name: CDK Synth
        run: cdk synth
      
      - name: CDK Deploy
        run: cdk deploy --require-approval never
      
      - name: Get API Gateway URL
        run: |
          echo "✅ Deployment completed!"
          echo ""
          echo "📍 API Endpoints:"
          API_URL=$(aws cloudformation describe-stacks \
            --stack-name BlsCdkAppStack \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
            --output text)
          echo "API URL: $API_URL"
          echo ""
          echo "Test your API:"
          echo "  curl $API_URL/api/books"
          echo ""
          echo "Add a book:"
          echo "  curl -X POST $API_URL/api/books \\"
          echo "    -H 'Content-Type: application/json' \\"
          echo "    -d '{\"title\":\"Clean Code\",\"author\":\"Robert C. Martin\",\"isbn\":\"978-0132350884\"}'"

